# The URL the site will be built for
base_url = "https://example.com"
title = "Tech Startup"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
app_base_url = "https://app.cloak.software"
start_year = "2021"

# Every page CTA. At the bottom of every blog post we have a cta
every_page_cta = { title = "Your 30 seconds away from trying us out", cta_url = "/blog", cta_button = "Sign Up" }

# On the footer we have a signup button and a call to action, set the text here
footer_cta = { title = "Sign up for our service", prompt = "Get control of your secrets and add security.", cta_url = "/blog", cta_button = "Check it Out" }

# Where shall we point the sign in and sign up buttons.
authentication = { signup = "/auth/sign_up", signin = "/auth/sign_up" }

# Information required by terms and privacy pages.
support_email = "support@tech-startup.com"
company_address = "71-75 Shelton Street, London, LND, WC2H 9JQ, United Kingdom"

# Social icons (shown on the footer)
github_repo = "https://github.com/purton-tech/tech-startup-theme"
twitter = "https://twitter.com/ianpurton"
linkedin = "https://www.linkedin.com/in/ianpurton/"

# Resources on the footer (LHS)
resources_1 = [
    {name = "Blog", url = "/blog"},
    {name = "Documentation", url = "/documentation"},
    {name = "FAQ", url = "/blog"},
]

resources_2 = [
    {name = "Pricing", url = "/pricing"},
    {name = "Mission", url = "/blog"},
    {name = "Careers", url = "/blog"},
]

menu_items = [
    {name = "Pricing", url = "/pricing"}
]
